source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
use_frameworks!
pod 'GoogleMaps'
pod 'FBSDKCoreKit','4.5.1'
pod 'FBSDKLoginKit','4.5.1'
pod 'Onboard'
pod 'Masonry'
pod 'ChameleonFramework'
pod 'DZNEmptyDataSet'
pod 'FontAwesomeKit'
pod 'Parse'
pod 'ParseUI'
pod 'ApiAI'
pod 'PulsingHalo'
pod 'ParseFacebookUtilsV4','1.8'
